Update SimplifiedCharts.md to Unicode 15.0
hfhchan/irg pull request #209
Opened 2023-01-26 21:33 UTC by graphemecluster

2023-01-26 23:19 UTC, hfhchan requested changes

2023-01-26 23:19 UTC, hfhchan commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
?

2023-01-29 06:03 UTC, graphemecluster commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
Why what I generated is different from you – did you remove them explicitly before?

2023-01-29 07:18 UTC, graphemecluster commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
Should 黄 also be removed? If so, how about 丬 (`90.0 90'.0`)?

2023-01-29 08:12 UTC, hfhchan-plb commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
>  You generated them by writing a script right?

I think I did them manually LOL

`U+8FB6` should be corrected in newer version of Unihan.

I think we can keep 黄, same case as 丬 basically.

2023-01-29 10:29 UTC, graphemecluster commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
Did you use the wrong account again 😂

2023-01-29 12:04 UTC, hfhchan commented on SimplifiedCharts.md
> +U+8FB6	kRSUnicode	162'.0
> You generated them by writing a script right?

I think I did them manually LOL

U+8FB6 should be corrected in newer version of Unihan.

I think we can keep 黄, same case as 丬 basically.

2023-01-29 12:04 UTC, merged